### ISSUE TITLE
build-osx.sh -> Update to recommended settings -> build-osx.sh -> Update to recommended settings

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#114]
pingpong going on between `build-osx.sh` and Xcode.

Basically, if I run build-osx.sh, and then boot up Xcode, Xcode will ask me to make some changes (`Update to recommended settings`) to vst2,vst3,au. if i then clean+build in xcode, and quit xcode, and run build-osx.sh, xcode will, yet again, ask me to Update to recommended settings.

Is there some way of evading this, so that one doesn't need to update to recommended settings every time?

**Comment by kzantow** [comment]
Is this for Xcode 10? It doesn't happen on Xcode 9. I'm not sure if there's a specific preference, but 9 is the last version that will build 32-bit, if there was any desire to distribute 32-bit versions, which might make it a reasonable target...

**Comment by esaruoho** [comment]
@kzantow i think it makes sense to push out 32bit ones too, just in case ppl are using older macs

**Comment by baconpaul** [comment]
Really? How old does your Mac need to be to not support 64 bit audio units or vsts? I’m fine embracing the future a bit and not killing ourself with another 3 packages to build and test if others are!

**Comment by esaruoho** [comment]
@baconpaul f.ex. there are people still running 32bit Ableton Live and 32bit Renoise.. because they eat less CPU. If it is a non-issue to build 32bit plugins automatically (set-and-forget), then it would be of use for sure.

**Comment by baconpaul** [comment]
Huh.  Well warnings on pointer size will matter a lot I guess. We should turn to those one day.

**Comment by baconpaul** [comment]
Anyway to your original question; no there is no way to avoid this. Every time you run premake it requires you to update in Xcode 10.

The solution is to patch premake core so it emits Xcode 10 files which is a lot of work or run premake less often. The first is not a surge issue. The second is in the hands of the users.

I am resistant to doing something like if -f surge.xcworkspace don’t run premake since premake is always rhebsafe thing to do.

**Comment by esaruoho** [comment]
closing as "expected behaviour" :)
