### ISSUE TITLE
Set up IRC logging

### ISSUE THREAD

**Issue by jsakkine** [kurasu/surge#120]
Many of the issues are not actually issues/tasks but merely discussions. I think it'd be good idea to set up mailing list. I found this: https://www.freelists.org/. Any other comparable service would be fine too.

**Comment by jsakkine** [comment]
One example: https://github.com/kurasu/surge/issues/112

**Comment by baconpaul** [comment]
I have no objections! If you do this and send a PR to the README.md with appropriate instructions on how to sub and stuff we can sweep that in. And I would join the list!

**Comment by esaruoho** [comment]
imho this current github-tickets / PRs as conversations is good because anyone can chime in anywhere. if you're not on the mailinglist, you don't know what's going on in there. here you can reference code directly, everyone sees the reference, it can be modified on-the-go. i've found these conversations fruitful and would have a great deal of trouble following them in a mailinglist environment where most of the time there's maybe 2-3 people there as opposed to 4-6. and code-reviewing PRs is pretty important to keep conversant, rather than "if i bump into a bug, i'll post it to the mailinglist, which person x who can fix it bug, doesn't read, it never gets fixed".

i've seen people try to split communication into telegram,slack,discord,signal,whatsapp,facebook groups,phpbb2 forums and it never works - 25% of the people involved adopt it, then it dies, then it hinders communication. here everything is at your fingertips, the repo, the commits, the PRs, the forked repos and their branches, direct linking to everywhere. 

granted, i've not seen a github repo this verbose before, but i don't find it confusing, it's just different.

**Comment by jsakkine** [comment]
Soon to be closed as soon as @esaruoho parts out the channel :) Then I set up ChanServ there and we get logging.

**Comment by esaruoho** [comment]
@jsakkine i just left the channel

**Comment by jsakkine** [comment]
OK, so now I have ChanServ there and I get ops from it so the channel can be rejoined again. I will enable the logging a bit later today.

**Comment by jsakkine** [comment]
https://freenode.logbot.info/surgesynth/ there it is.

**Comment by baconpaul** [comment]
Mind tossing in a pr to update the readme sometime?

**Comment by jsakkine** [comment]
Done :)

**Comment by baconpaul** [comment]
Thanks!!
