### ISSUE TITLE
suggestion: if wavetable has LFO applied to it - modify wavetable visual on top-left-corner

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#139]
suggestion: if you map a LFO to the wavetable ((Shape)) - offer the user the capability of seeing the wavetable modified on-the-fly.
and to disable that if the user so chooses.

**Comment by baconpaul** [comment]
Looking at the code, I think that would be hard. The redraw code samples the oscillator once and blats out the entire bitmap. It's not like it is observing the signal realtime and tracing it scope style. So which part and cycle of the LFO would you use? When is the LFO triggered to make the display? etc...

Or maybe you are thinking of something else?

*BUT* reading the code did make me realize that the COsicllatorDisplay has the same RGBA ordering problem that made the CLFODisplay not show up. That's why the waveforms are that gross green and red. I fixed it in PR #140 which is a plus!

**Comment by baconpaul** [comment]
<img width="760" alt="screen shot 2018-12-22 at 9 12 06 pm" src="https://user-images.githubusercontent.com/13387561/50380214-3e993100-062e-11e9-9ac7-2cc1e9f32ca2.png">

See? Isn't that better!

**Comment by esaruoho** [comment]
![surge_vv](https://user-images.githubusercontent.com/4966687/50454068-c7c1a800-094d-11e9-8292-e2596eae6297.gif)

this thing here
followed by what happens when i map a LFO to shape (nothing happens visually)

**Comment by baconpaul** [comment]
Right I got that. But what should happen? There’s not an obvious behavior since that display is not an oscilloscope. 

BTW: Nice gif! How did you make that?

**Comment by esaruoho** [comment]
@baconpaul the app i use is called Licecap, and it is a gorgeous app to have available to oneself for testing purposes.. check https://www.cockos.com/licecap/ out

**Comment by esaruoho** [comment]
@baconpaul well, yeah, what i was suggesting (now that i think about it more clearly, sorry) was that if an lfo is sending parameter changes to sliders, that the sliders update in realtime. and if they then update in real-time, the wavetable will "function "like" an oscilloscope". but that if it is extremely cpu hungry, it would be good to not have that.

but anyway, i'm fine with it never being added in, it's just a thought, just like the other feature requests i'm posting :)
