### ISSUE TITLE
LFO FreeRun doesn't in AU Host

### ISSUE THREAD

**Issue by baconpaul** [kurasu/surge#146]
So fixing the step sequencer I put it in freerun mode so that it would, well, freerun and sync. But it still key triggered.

Looking at the code it seems nothing ever sets the run mode to `lm_freerun`

```
paul:~/dev/music/surge$ grep -r keytrigger src
src/common/SurgeStorage.h:   lm_keytrigger,
src/common/gui/CLFOGui.cpp:         tp[lfodata->trigmode.param_id_in_scene].i = lm_keytrigger;
src/common/dsp/LfoModulationSource.cpp:      case lm_keytrigger:
paul:~/dev/music/surge$ grep -r freerun src
src/common/SurgeStorage.h:   lm_freerun = 0,
src/common/dsp/LfoModulationSource.cpp:      case lm_freerun:
src/common/dsp/LfoModulationSource.cpp:   /*if (lfo->trigmode.val.i == lm_freerun)
paul:~/dev/music/surge$ 
```

so another bug to fix I think. It may be just that the GUI doesn't set the flag properly and then it all works (so it is in CLFOGui.cpp) but that commented out bit in the modulation source may also be part of it.

**Comment by inigokennedy** [comment]
Not sure if it is directly related, FreeRun does work (at least in some cases) but it also resets rather than genuinely free runs so if you are running in short loops it constantly restarts. From the code it looks like it is tied to _songpos_ which would explain that - not desirable for genuine free run in my opinion (and one of my pet peeves over the years) but not sure if it can be counted as a bug.

**Comment by baconpaul** [comment]
Right. I will dig more but the thing that made me say this was I put a step sequencer in free run mode and bound it to pitch. I press c and it beeps and boops. When I hold down an e in a bit with the c depressed I expected them to be synced - if the sequencer was free running the keypress on the new voice should change the lfo start position - but that was not what happened. Rather it retriggered for the new note

So I put in the bug. When I have a bit of time I’ll read the code and see what it is doing.

Curious what sort of configuration shows the behavior you see? Or do you have a patch file?

Thank you!

**Comment by inigokennedy** [comment]
I wonder if what you describe is a Temposync bug. With Temposync on the modulation rate then the modulation of multiple note triggers is synchronised (it's like Temposync is absolute rather than relative - maybe this is where _songpos_ comes into it and in effect every voice is locked to the same base rather than being independent). I would say this is incorrect behaviour although it might be the only sane solution. If you don't use Temposync on the modulation rate then I think the modulation is correct and for each note things stay independent. Harder to describe than hear I guess. It could all point to a behaviour in that something in the LFO code is based on a common reference point like _songpos_.

**Comment by baconpaul** [comment]
Right so the code for freerun does set phase off of songpos.

Here's kinda what I'm expecting. Imagine I have a square wave LFO. It is on or off. In ascii art I will describe that as `^^__^^__^^__` for 3 cycles.

In key trigger mode if I play two notes at different times (here N1 and N2) I expect their voice LFOs to look like this

```
N1  ^^^^____^^^^____^^^^____^^^^____
        N2 ^^^^____^^^^____^^^^____^^^^____
```

whereas if I am in free run mode and I press the two notes I expect something more like this

```
N1 ^^^^____^^^^____^^^^____^^^^____
      N2 __^^^^____^^^^____^^^^____
```

because the single LFO is running at a phase which is independent of keypress and is driven by songpos.

That way you can have polyphonic but synchronized modulations

If you look in dsp/LfoModulationSource.cpp you see

```
      case lm_freerun:
      {
         double ipart; //,tsrate = localcopy[rate].f;
         phase = (float)modf(
             phaseslider + 0.5f * storage->songpos * pow(2.0, (double)localcopy[rate].f), &ipart);
         int i = (int)ipart;
         step = (i % max(1, (ss->loop_end - ss->loop_start))) + ss->loop_start;
      }
      break;
```

but that's only in the initialization and attack section. You see the same code commented out later in the ::process_block (around line 239 in current master).

But my real question is: If you understand my ascii art is that the behavior you see?

Like if I made a patch with a super slow square wave LFO in freerun mode bound to pitch and I pressed a key so it went up and down a 3rd, and half way through a transition I press a second key, they flip at the same time?  Because when I make exactly that patch at head there's really no difference between freerun and key trigger.

**Comment by baconpaul** [comment]
OK so I figured out what's going on here. The problem is entirely in the AU implementation of transport and timecode. I'll get a fix PR together in the next week or so.

**Comment by inigokennedy** [comment]
Great find! Yes, the VST seems to behave OK in this respect from memory (away from studio at the moment). I’m on Win x64 so no AU to test against. Those ascii diagrams were spot on and reminded me of beta testing Claes’s ShortCircuit many years ago; I described a timing bug in a very similar way :D

It’s behaviour by design that freerun phase is driven by songpos and it has its advantages (predictability) but it would be an interesting feature change to implement phase independent of songpos (unpredictability). For a separate Issue though.

**Comment by baconpaul** [comment]
Yeah songpos to freerun is absolutely the right behavior. Unless transport is stopped! That was basically the au bug.
