### ISSUE TITLE
Waveshaper asymmetric/ASSYM-mode glitches with (at least) two patches

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#181]
`Pluck (fast) -> Molusk`
`Polysynth -> FM Poly 1`

both use ASSYM -mode, which causes glitches. 

`FM Poly 1`: just hold down one note, then play another note. audible click/pop.
`Molusk`: Either hold down a note and play other notes quickly, or just play notes quickly, you'll hear an audible click/pop or resonance glitch or wotever.

original description for `Molusk`:
```
Getting some glitching: patch "Molusk" in "Pluck (fast)". 
...Playing a few notes fairly rapidly (8th notes) glitches out 
after about 9 notes (though the count varies).
It's the waveshaper. If you turn it off, no more glitching.
(The patch has it on Asymmetric, FWIW)
And, yup, if I turn other patches on ASSYM, causes glitching.
(The level of the waveshaper drive doesn't seem to make any difference.)
All of the other modes seem to behave just fine.
```

and for `FM Poly 1`
```
Select preset "Polysynth - FM Poly 1" and play just two notes legato - 
second one will glitch.
```

**Comment by esaruoho** [comment]
another `ASSYM` bug:

Load `Polysynth - FM Poly 1` and play and hold down one note, then play another note. the other note will click/pop.

**Comment by baconpaul** [comment]
These are great. Do we know platform version build number daw etc for the user? 

Clearly that “build info in about” will matter as people start using this.

**Comment by esaruoho** [comment]
@baconpaul @getdunne reported the FM Poly 1 bug on Win32. I have seen both patches bug on macOS 64-bit AudioUnit. so this isn't a platform version or 32bit/64bit version.

**Comment by esaruoho** [comment]
newest build from `master` shows these behaviours, best fastest example is `Polysynth>FM Poly 1`

VST2: Renoise
AU: Ableton Live
AU: Logic Pro X

**Comment by kzantow** [comment]
Thanks for tracking this down to Surge-wide @esaruoho I'll see if I can scrape some time to figure out what's problematic with this stuff after getting all the installer (#180) stuff worked out

**Comment by baconpaul** [comment]
OK I have a partial fix for this which also explains why VST2 and AU are broken and VST3 isn't.  Hold on for me to assemble it all together for at least AU and then you can do same with VST2, even though it's not a complete fix.

**Comment by baconpaul** [comment]
Alright so there's a compound problem here. 

In QuadFilterUnit.cpp you can see this code to return the function pointer for the shaper

```
   case wst_asym:
#if !_M_X64
      if (!(CpuArchitecture & CaSSE2))
         return ASYM_SSE1;
#endif
      return ASYM_SSE2;
```

so I went and put a debug hook in ASYM_SSE2 and it didn't fire. My mac AU was calling ASYM_SSE1.

The reason for this is because, even though initCpuInfo would set my machine to SSE2 (since all intel macs support SSE2), it was never being called. 

In VST3 initCpuArchitecture is called in the startup path due to a call to AbstractSynthesizer::initDllGlobals which which in itself is called from src/vst3/surgeentry.cpp. So on a mac the VST3 plugin should have not exhibited this behavior.

So I put a call to initCpuArchitecture in the aulayer and voila we used the SSE2 wave shaper. Then the bug went away. Which means the *fundamental* bug here is that ASYM_SSE1 and ASYM_SSE2 in QuadFilterUnit are not doing the same thing.

But it means the proximate thing we can do is make sure initCpuArchitecture is called through all the entry points. It is now called properly through the auLayer entry point but someone who can build and test vst2 needs to put it in there. 

My guess is, at line 31 of Vst2PluginInstance.cpp you put a call to initCpuArchitecture(), after having done a `#include "CpuArchitecture.h" above, and VST2 will work also.

As to whether we need to debug the SSE1 implementation I'm not sure.

But note this also fixes another pretty big bug, that the VST3 and Windows code which most people were running was not the mac AU audio code. So that's now resolved. Or will be when I sweep in that one like aulayer PR I'm about to do!

**Comment by baconpaul** [comment]
Oh hey I was looking at how @kzantow did builds in azure pipeline. And now I can also test VST2, so was able to confirm that, yes, the same problem which made it pop in AU makes it pop in VST2, and the fix above corrects it.

So I'm going to close this issue. We are fixed all hosts now.
