### ISSUE TITLE
Global GUI: Please change bmp00144's width from 135px to 136px

### ISSUE THREAD

**Issue by cyanit** [kurasu/surge#203]
Problem coming up while vectorizing: bmp00144 has a really strange size. I don't know if its possible, but id like to enlarge it by exactly one pixel, so it can be divided by 4. 
Its width is 135px, its height 108px. You can't fit 4 buttons with the same size within it withouth them having some weird floating-point width, which is not ideal. I think the necessary code adjustment will be worth it.

**Comment by cyanit** [comment]
Here you go:
1x
![bmp00144](https://user-images.githubusercontent.com/26248671/50687730-bd28a200-1022-11e9-9b7a-2af4e2d6e720.png)

2x
![bmp00144@2x](https://user-images.githubusercontent.com/26248671/50687736-c154bf80-1022-11e9-8623-68a5450fa82e.png)

3x
![bmp00144@3x](https://user-images.githubusercontent.com/26248671/50687767-d9c4da00-1022-11e9-97ed-08e474f6cd24.png)

These are not the final colors, i have to fiddle with the off state a bit more. Also, I think ill round them at 3 or 4 pixels instead of 2.

**Comment by cyanit** [comment]
No problem! In affinity designer all you do is add another export at 1.5x size. Heres a screenshot of how it may look like:
![fxbtns](https://user-images.githubusercontent.com/26248671/50688370-6a9cb500-1025-11e9-803a-826de4fcdd2e.PNG)

**Comment by baconpaul** [comment]
I think the spacing between buttons is really nice. I worry at the 1.0 size you may need a bit more contrast. For fun, I dropped in your 1.0 bitmap and set the size to 136 rather than 135 and this is what it looks like for me.

<img width="326" alt="screen shot 2019-01-04 at 9 11 20 am" src="https://user-images.githubusercontent.com/13387561/50692136-e59fa480-1000-11e9-9fee-04d184208090.png">

vs the original

<img width="236" alt="screen shot 2019-01-04 at 9 13 27 am" src="https://user-images.githubusercontent.com/13387561/50692180-05cf6380-1001-11e9-9252-abbd6cb458d8.png">

but I also realized this is happening on the "136" thread not the main #23 thread. So let me propose that I close this issue, since yes 136 px is fine and when we have the image set we can do the change trivially, and then we can have the discussion over there. Sound good?

Thanks!
