### ISSUE TITLE
Automation Hosts learn the wrong names (Live, Bitwig, VST2, AU)

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#247]
Steps to replicate:
1. Launch Ableton Live
2. Load Surge (VST or AU)
3. Click on "Configure"
4. Move a slider in Surge

Expected result:
the slider's slider will appear in Ableton Live

Current Result:
the slider's slider appears, but when you let go of tweaking the slider, another "twin" slider appears.

![surge_ableton_live](https://user-images.githubusercontent.com/4966687/50925370-d6828180-145a-11e9-9a4b-5ec0197573fa.gif)
![surge_ableton_livev2](https://user-images.githubusercontent.com/4966687/50925373-d8e4db80-145a-11e9-8be7-a3bb8ab67424.gif)

for instance,
`Filter EG Decay` "twin" is `LFO4 Deform`
`F2 Cutoff` "twin" is `LFO 3 Rate`
`FX1 Send` "twin" is `F2 Envmod`
`Output Pan` "twin" is `F2 Resonance`
`F2 Resonance` "twin" is `LFO3 Magnitude`
`F2 Keytrack` "twin" is `LFO3 Unipolar`

and so on and so on.

**Comment by baconpaul** [comment]
Any way to get a demo version of live? I’ve never used it.

**Comment by esaruoho** [comment]
@baconpaul https://www.ableton.com/en/trial/

**Comment by baconpaul** [comment]
I think this and #193 sound super similar right?

**Comment by esaruoho** [comment]
@baconpaul well it could be related, if bitwig is a kind of "only one can get bound with a click" (i.e. it discards the first one of the "two" bindings)..

**Comment by esaruoho** [comment]
@baconpaul to know for sure, i'd have to have bitwig installed..

**Comment by baconpaul** [comment]
OK so in bitwig I just automated Filter EG Decay and got the binding to only one thing, which was LFO4 Deform. So bitwig and Live are doing the same thing.

Which means this and #193 are the same problem.

And which means I can debug it because I can use bitwig!

Note that the vst3 in bitwig basically totally doesn't work on automation.

So definitely something interesting here.

**Comment by baconpaul** [comment]
OK I'm going to consolidate into one issue. From #193 

> From aMUSEd on kvraudio:
> There is something odd going on with host automation assignments for Scene B. If I try and 'learn'  params from the filters in scene B in Bitwig for example (in order to create a device panel map), by clicking learn then selecting the filter cutoff, res etc, what gets learnt is LFO params, not filter params. The only way to map filter params (or any params from Scene B) is via the drop-down selector but that is an endless list and very disorganised.

**Comment by baconpaul** [comment]
Ahh the host calls AudioEffectX::beginEdit and ::endEdit around the move. I bet that path will lead me there.

**Comment by baconpaul** [comment]
OK I absolutely know the problem here now. But I don't quite know the fix.
The controls in SurgeGuiEditor are made with a tag that adds "start_paramtags" to it. So the tags are off by about 50.

In SurgeGuiEditor::beginEdit() it strips this off. But that function isn't called.

Instead the beginEdits come from CControl which doesn't know to do the transformation.

So we need to do the "- start_paramtags" somewhere else too; probably in the ::beginEdit in the Vst2Host. But start_paramtags is local to the .cpp file so I need to figure out the right function I can call from src/vst2.

But very close on this one.

**Comment by baconpaul** [comment]
![automate](https://user-images.githubusercontent.com/13387561/51045573-e781de80-1591-11e9-9749-4a3d03dfb709.gif)

Yup that's exactly it

So let me put my code back together and then I will make a PR for @kurasu to review that fixes VST2. Then we have to fix VST3 and AU I guess

**Comment by baconpaul** [comment]
Got it working on Logic also.

![automate-logic](https://user-images.githubusercontent.com/13387561/51065990-c7740e80-15d5-11e9-81de-e60862e4aa7f.gif)

I think it's just VST3 that has a problem now.

**Comment by esaruoho** [comment]
thanks for the lovely fixes on this ticket, @baconpaul
