### ISSUE TITLE
Poly counter / limiter does not actually limit. Even if you have Poly 0/8 - you can play up to 12/8 according to the detector

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#256]
one for @baconpaul on the Poly counter/limiter:

Steps to replicate:
1. Launch Surge, increase release of patch so that there are longer notes
2. Play three notes, see `3/8`
3. Quickly play 12 notes, see `12/8`
4. Quickly play 10 notes, see `10/8`
5. Now set Release to max.
6. Hammer in 15 notes quickly
7. ~Watch the Poly counter fluctuate between `10/8` and `0/8`, never really settling.~ this no longer happens as of jan11th 2019 builds

Therefore the `/8` segment is not a limiter of polyphony, apparently.

**Comment by esaruoho** [comment]
the fluctuation no longer happens, but the rest of the issue still applies

**Comment by baconpaul** [comment]
So I actually think this is mostly working. I just tried with latest build and I did the following

1. Load init (and turn on the LPF so it doesn't sound gross while I test)
2. take the release to max
3. set the poly to 2
4. start playing

and voila I only get two voices. So that works.

The problem is all when you fast play. If I take that same configuration and really mash on the keyboard I can get it to say it is playing up to 4 for me but I only hear two.  So it thinks it has voices going but those voices aren't making sound.

That makes it a bit harder to debug. But can you confirm you see that?

Not going to work on this one now. It looks tricky to fix!

**Comment by esaruoho** [comment]
hi @baconpaul -- i was stalking kvrforum again and found this

https://www.kvraudio.com/forum/viewtopic.php?f=33&t=155873&p=2188573&hilit=surge#p2188573

from `stefancrs`

```
That's what Claes does in Surge, isn't it? The poly
setting is a target, not a brick wall, and hence it
sometimes overshoot for short periods of time.
```

i guess we can leave this ticket, and close it, or what do you think @kurasu ? should the behaviour change to "brickwall"?

**Comment by baconpaul** [comment]
I do not think so. It sounded correct to me. I’m also not sure what I would change 

Poly2 played slowly with a long pad brick walls so I think close this one tbh

**Comment by esaruoho** [comment]
yeah, closing.
