### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by jsakkine** [kurasu/surge#44]
At the moment the code base is filled with a chaotic set of coding conventions. It would be good to have a well defined coding to which new commits would compared against. This would also make the patch review process more lean.

In order to move fast with this I would recommend to use some well defined style known to work in cross-platform projects e.g. https://webkit.org/code-style-guidelines. We could start for example with WebKit conventions and refine as we go.

Naturally, the existing code is how it is but this would be the convention for all future changes.

Other things to consider: the subset of C++ used (and related things like RTTI, most projects that aim for maximum portability do not use RTTI), external dependencies (are these allowed or not and in which circumstances) etc.

**Comment by jsakkine** [comment]
Even things like, which type of newline character should be used, ought to be defined. This is actually the most high priority item because pull request are already flowing in...

**Comment by asimilon** [comment]
No, just for auto formatting the source code to a chosen convention.  It means anyone contributing doesn't really have to worry about coding style too much, as long as they run it through `clang-format` before committing.

**Comment by jsakkine** [comment]
I prefer rather written guidelines. Don't even use clang for starters..

**Comment by asimilon** [comment]
You don't need to use clang in order to use clang-format.  Who on earth is going to trawl the entire code base applying code style otherwise?  I prefer computers do the boring stuff like that for me, and they don't make mistakes or forget once it's set up correctly.  On the other hand humans quite often do. ;)

**Comment by jsakkine** [comment]
It doesn't work like that in any open source project, at least not ones that I've actively worked. It is done patch per patch basis as part of the peer review process. You don't do commits just to change coding style.

Specific tool does not really replace a review process. Conventions can be also related to semantics like whether RTTI is allowed or not. Even with tooling you would have to first decide guidelines that you configure your tool to check. You cannot view this issue through some random utility.

**Comment by baconpaul** [comment]
This would be great to have.

The codebase is already getting pretty c++-11-y (and in some places c++-14-y) so I’d say “lets use C++14” and that means things like RTTI work but still have efficiency problems. But things like lambdas and std::function and so on work and can be used. (Since I used one to implement zoom I am particularly interested in this being true! :) )

A good setting that works for Xcode and emacs and meets your guidelines and an automatic formatting tool setting would both be wonderful. I’m pretty conscious of the fact that the PR’s I’ve been doing are a bit of a mish mash and it’s hard to match the code anyway.

Happy to follow any guideline the group suggests.

**Comment by jsakkine** [comment]
I'll close this now with the conclusion that it does matter but is too early. Once "everything works" (heh) we could write some high-level conventions to the `README.md`. ATM run-time is broken except for a small subset of platform/target combinations and even the build/packaging is somewhat flakky. This is better topic to discuss later.

I don't know if it is just me but only thing that really hurts my head is 3 spaces for tab :) In principle, there is nothing wrong with it but rest of the world uses 90% of projects either 4 character tabs with spaces or 8 character tabs with a tab character.
