### ISSUE TITLE
surge-au: Implicit conversion loses integer precision

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#48]
Getting this `Value Conversion issue` on `surge-au/libs/xml/tinyxmlparser.cpp` line 928, with the bit of code saying

`int tagIndex = tag->length();`

shooting

```
Implicit conversion loses integer precision: 'std::__1::basic_string<char, 
std::__1::char_traits<char>, std::__1::allocator<char> >::size_type' (aka
 'unsigned long') to 'int')
```

![tinyxmlparser_cpp](https://user-images.githubusercontent.com/4966687/49448283-3abd8000-f7e1-11e8-8c72-fc6393855391.jpg)

**Comment by baconpaul** [comment]
This warning goes away if you use size_t rather than int for tagIndex
Also (and this is on my Au-build branch) I replaced all the this && with a THIS_AND macro which is defaulted to blank since that was cluttering my life with warnings from the xml parser.
Don’t know if that will all make it into a PR but may help. Again you can see that over on the fork I posted on the other thread,.

**Comment by esaruoho** [comment]
cool, sounds like your `au-build` is going to be a huge improvement on the current state! i've been attempting to apply the various PRs and branches to a private branch in my own fork, but so far haven't made much progress :)

**Comment by esaruoho** [comment]
@baconpaul should i close this ticket, or does this warning still appear?

**Comment by baconpaul** [comment]
Yeah I think I got this one. But there are others just like it in the codebass.

Once my au fix is merged I may open a bigger issue to get Mac au warning free (which will require some -w flags but also some code changes) so perhaps close this now.

Thanks!!

**Comment by esaruoho** [comment]
closing for now
