### ISSUE TITLE
Filter Width Pan Slider doesn't invalidate properly

### ISSUE THREAD

**Issue by esaruoho** [kurasu/surge#75]
”Filter Width Pan Slider doesn't invalidate properly”

I'm slightly confused. I'm using #69 by @baconpaul and i'm actually seeing an empty slot for `Pan` - yet there doesn't seem to be a slider there? What am I missing?
Does a slider exist? @kurasu ? 
![screenshot_14_12_2018__17_30](https://user-images.githubusercontent.com/4966687/50012009-330e9000-ffc6-11e8-9748-a4d8dad6d569.jpg)

**Comment by baconpaul** [comment]
Huh I was about to add a comment like "do you still see this" but then I realized that I see it too.

However it isn't the pan slider that is missing. It is the "slider below pan".

```
   // pan2 control
   if ((synth->storage.getPatch().scene[current_scene].filterblock_configuration.val.i !=
        fb_stereo) &&
       (synth->storage.getPatch().scene[current_scene].filterblock_configuration.val.i != fb_wide))
   {
      i = synth->storage.getPatch().scene[current_scene].width.id;
      if (param[i] && dynamic_cast<CSurgeSlider*>(param[i]) != nullptr)
         ((CSurgeSlider*)param[i])->disabled = true;
   }

```
 
is the code that activates it. So when you set the filter configuration to "wide" it appears, kinda. You need to click to force a repaint. And when you turn off wide it doesn't undisplay.

So the bug here is a bit more subtle. It is that "wide mode on filter doesn't force draw; and disabled wide mode is blank". Ideally you'd make filter->disabled=true not be *so* disabled!

But more importantly when you toggle wide mode, you want to do a param refresh which forces a createOrRedraw. Something about the setDirty around line 1938 of SurgeGUIEditor isn't enough.

**Comment by baconpaul** [comment]
Actually @esaruoho can you rename this issue to "Filter Width Pan Slider doesn't invalidate properly" so we know what to fix?

**Comment by esaruoho** [comment]
@baconpaul i updated the title and will look again so can rewrite the original ticket. Thanks for the sleuthwork!

**Comment by baconpaul** [comment]
Thanks @kurasu - the invalidation code means it doesn’t immediately toggle on off when you go into and out of wide, so there’s a tiny bug let there somewhere, but we can fix that soon enough I’m sure!

**Comment by baconpaul** [comment]
Fixed at head; closing.
