### ISSUE TITLE
Support and optimization for recent CPU instruction sets 

### ISSUE THREAD

**Issue by lunafreya** [kurasu/surge#8]
As this synth is last updated around 2008 or 09-ish (I don't know when version 1.5.1a was released), the code must have been dated for use with processors that are in the retail market at that time, and might not play nice with today's processors like AMD's Ryzen series (in market since early 2017), as well as Intel's recent seventh and eighth generation Core i3/5/7/9 processors.

We need to optimize the code in order to ensure that the synth will work perfectly with modern processors.

The synth's underlying code will need to be modified or (if necessary) rewritten, in order to take full advantage of new CPU instruction sets found in recent processors (including AVX2, AVX512, BMI1 and BMI2).

**Comment by kurasu** [comment]
there's really not as much benefit to this as you'd think, it's already vectorized on 128-bit vectors. Going SSE4.1 could help some (it has direct floor/ceil/round calls without switching fpu mode) but would need to deal with compatibility with older machines (multiple binaries etc) so it might not be worth the effort.

Going wider with AVX1 (not 2, it's for ints) would be a lot of work. It could speed it up slightly on intel, but it wouldn't be any quicker on Ryzens as it just has 128-bit units (lots of them) so unless its instruction decode limited (highly unlikely) it would probably just end up being a few percent slower due to cache issues (from restructuring the code and data layout to work in vectors of 8 floats).
