### ISSUE TITLE
Vector Drawing in the UI

### ISSUE THREAD

**Issue by baconpaul** [kurasu/surge#91]
Now that we have issue #81 implementing a zoom (AU Mac only right now, I'm sorry; If you want to work on making it work VST or Win/Lin tag me on an issue and I'll give you guidelines if it's not clear from that issue), I am thinking about replacing elements with vector elements. Putting this issue in place to be the placeholder for my plan in case anyone has feedback.

In issue #23 @cyanit has shared SVG version of the bitmap (actually PNG) assets. I'm wondering if I can use them.

I'm going to start by seeing if I can just replace the horizontal background on a fader. But there's a lot of work to make that happen since the CBlahDeBlah world of vstgui doesn't have an SVG renderer.

But it does have canvas components with a ::draw( CDrawContext * ) method; and as we know from the screenshots in #81 if you call the draw methods directly they scale with vector style, as you would expect.

So here's my rough plan

1. Implement a super-tiny subset of SVG (just paths and groups probably) using tinyxml and make a common/gui/CSVG.cpp and h which kinda like Bitmap holds a drawable asset

2. For one of the bitmaps in CSurgeSlider - maybe even just a handle - replace the bitmap with my svg thing, have the svg thing also be in the resources bundle, and hack away until it works.

3. commit || give up

4. If (! give up ) figure out a plan to distribute the vectorizing work. Gulp!

The weird thing I notice is that the bitmap assets contain multiple views. I haven't quite figured out how you pan around the views in the UI yet. For instance bmp00154.png (which is IDB_FADERH_BG) has all of these in it. So also want to dig around on how pTray moves around the bmp before it paints.

![bmp00154](https://user-images.githubusercontent.com/13387561/50058263-b3a6cb00-0143-11e9-825d-469472c59c8e.png)

Welcome any comments. I'm going to do this off on a branch so as to not mess up au-cocoaui-build and so on while @esaruoho and @kzantow try to get the big pull request together.

**Comment by baconpaul** [comment]
Oh the answer to how you move around is pretty simple. Look around like 158 of CSurgeSlider.cpp and you see that the one you choose to draw is controlled by typex and typey which move you around the image space before drawing. So that should be pretty easy to keep in place if the SVG draw image which I am imagining does the same thing. (Big if)

**Comment by kurasu** [comment]
This kind of assets could be done with draw commands rather than SVGs. That way we also have control over the pixel grid so we could do non-integer scaling without going to blurry-town. But not all of them are this easy.. 

Another option would of course be to use large (400%?) bitmaps instead and resample as needed. That might be the simpler approach.

**Comment by baconpaul** [comment]
Right. I thought about that. But svg rules basically are draw commands that editors can edit.

The way rack does it - which I am close to having work on a branch - is to use nanosvg to parse svg then walk the parse tree ejecting draw commands based on the contents. Rack outputs nanovg commands but I am close to outputting vstgui equivalents

Then I add a class which subclasses vstgui::cbitmap to try svg first and fall back to bmp

If you look in baconpaul/vectorized-draw you will see the start of what I mean but if you give me another 2 days Ill have it working.

This also allows us skins since we can easily have different resource sets since we have more control over the resource loading.

And then basicallyfolks go bitmap to svg with exact same size and voila drop in and run

You don’t happen to have the original assets for the bitmaps do you? Did you use photoshop or anything when you did it?

Thanks again for the merge!

**Comment by kzantow** [comment]
@baconpaul you're a best at this stuff. :) definitely agree SVG would be a nice way to go that would also allow for skinning fairly easily.

**Comment by baconpaul** [comment]
Hey @kzantow if you want to see how I'm thinking about vector drawing the new branch in baconpaul called "svg-drawing-91" has the code. This will actually load and kinda draw an SVG asset for one of the bitmaps.

Looks like garbage. My drawing code is stupid. But has the plumbing in place.

Again, just if you are interested.

On and if you get it you will need to do a git submodule update --init --recursive again since I added a new submodule.

**Comment by kurasu** [comment]
I started converting some of the old PSD source images I had to vector versions, starting with the background image. I'm using the branch "kurasu/assets" for this. I could easily provide a few more soon like the sliders so anyone who wants to work on a high-DPI version has the material he needs.

I think for Surge the best (or at least the easiest, from a theoretical POV) approach for scaling is the "apple-style" scaling, which is to render the GUI by an integer scaling factor (with assets provided for every supported scaling factor) optionally followed by an image resampling step in order to support non-integer scaling. So to scale 250%, you would render the GUI at 300% offscreen, than scale that down to 250% before putting it on the screen.

There problem with using a non-integer scaling is that you get a lot of rounding errors in your layout which you need to account for, and unless you have a design system really made from the ground up to support this (like we did for bitwig) you really can't, and will end up with things not aligning properly and so on. There are also design issues which affect the look a lot like what should happen with 1 pixel lines (at 150% scaling, should it be 1 or 2 pixels?). Using an integer ratio solves this because the whole image is rendered in a perfect state first, and even if the rescaling will make thin lines more blurry, it will make it consistently so and spacing of all elements will be correct.

There are also issues with using SVG as the format to represent the graphics in its current state, its not rich enough to support everything that is used. Even a simple drop shadow will make it revert to rasterization on export (at least in affinity designer) and if we want to allow skinning then designers won't enjoy this limitation. And although SVG can fallback to embedding pixel data, if it always does it then what's the point.

Now, I haven't looked through the VSTGUI code to see if there's an easy way to do this, could turn out to be a nightmare but I suspect it isn't.

**Comment by baconpaul** [comment]
400% bitmap assets would solve a lot of problems. At least in the au host the scale operation you describe is remarkably easy. It’s basicalky how I baked zoom in already. Kinda started whacking it into vst3 also.

Agree with the problems with svg. They are limited and the code to render them in vstgui is not as much fun to write as I was hoping even though I have it starting to kinda work. Nightmare is too strong - but not unwarranted. The cdrawcontext api matches the svg api fairly well.

I would be happy to abandon svg and go with multi-zoom bitmaps tho. Appreciate the assets and will take a peek after the holidays.

**Comment by kzantow** [comment]
seems like just having a couple zoom levels would be easiest. like just a button to zoom 200% either on or off.

**Comment by baconpaul** [comment]
Thank you!

I think what would be most useful is the current bitmaps at 100, 150, 200 and 300% with the exact same naming convention just in sub folders. So

Resources/scaled-bitmaps/100/bmp0143.png

And the like

There’s a long list of tiny bugs I want to squash first but then I’ll turn to scaled bitmap zoom rather than svg render (my original plan). Having the sssets would be awesome

If that works then we can talk skins post 1.6

The asset branch has original files I think

Thank you!

**Comment by itsmedavep** [comment]
Sounds great. Ill get started recreating the bitmaps as vectors tonight. 

At this point it would seem reasonable to start a separate issue for this work and track it there. 

Happy to help!

PS Would it be advisable to get another issue started to track this work? Im not sure this is the right one for that.

**Comment by cyanit** [comment]
> Sounds great. Ill get started recreating the bitmaps as vectors tonight.
> 
> Happy to help!
> 
> PS Would it be advisable to get another issue started to track this work? Im not sure this is the right one for that.

hey, I've opened one up a while ago regarding this, its #23 .

**Comment by baconpaul** [comment]
Let’s consolidate on #23 and I will re-title it now, closing this one.
